main: pl.noip.evaldor.Evaldor
name: Evaldor
version: 0.1
description: Evaldor
commands:
  gamemode:
    description: 'Zmienia aktualny tryb gry.'
    usage: ' [gracz] <tryb gry>'
    aliases: ['gm']
  time:
    description: 'Pozwala na kontrole czasu.'
    usage: ' <day/night>'
  weather:
    description: 'Komenda do kontroli pogody.'
    usage: ' <get/sun/storm/thunderstorm> [swiat] [czas w tickach]'
  evaldor:
    description: 'Glowna komenda pluginu.'
    usage: ' <reload>'
  spawn:
    description: 'Teleportuje na spawn.'
    usage: ' [nazwa spawnu] [gracz]'
  setspawn:
    description: 'Ustawia spawn.'
    usage: ' [nazwa spawnu]'
  lot:
    description: 'Pozwala na latanie bez trybu Creative.'
    usage: ' <on/off>'
    alias: ['fly,latanie']
  heal:
    description: 'Komenda sluzaca do leczenia siebie i innych graczy.'
    usage: ' [gracz]'
  feed:
    description: 'Pozwala na karmienie siebie i innych graczy.'
    usage: ' [gracz]'
  sethealth:
    description: 'Ustawia ilosc punktow zycia podanego gracza.'
    usage: ' [gracz] <ilosc punktow zycia>'
  sethunger:
    description: 'Ustawia ilosc punktow glodu podanego gracza.'
<<<<<<< HEAD
    usage: ' [gracz] <ilosc punktow glodu>'
=======
    usage: '/sethunger [gracz] <ilosc punktow glodu>'
  setsaturation:
    description: 'Ustawia ilosc punktow nasycenia podanego gracza.'
    usage: '/setsaturation [gracz] <ilosc punktow glodu>'
>>>>>>> fbed0b7609addbdc5bbb1338c905f4f5f65b95e7
  tp:
    description: 'Teleportuje gracza do gracza.'
    usage: ' <gracz 1> [gracz 2]'
  tpa:
    description: 'Wysyla prosbe o teleportacje do innego gracza'
    usage: ' <gracz>'
    alias: ['tpaccept', 'tpdeny']
  say:
    description: 'Wysyla podana wiadomosc do wszystkich graczy'
    usage: ' <wiadomosc>'
    alias: ['broadcast']
  /stop:
    description: 'Wylacza serwer'
    usage: ' [wiadomosc]'
