main: pl.noip.evaldor.Evaldor
name: Evaldor
version: 0.1
description: Evaldor
commands:
  gamemode:
    description: 'Zmienia aktualny tryb gry.'
    usage: '/gamemode [gracz] <tryb gry>'
    aliases: ['gm']
  time:
    description: 'Pozwala na kontrole czasu.'
    usage: '/time <day/night>'
  weather:
    description: 'Komenda do kontroli pogody.'
    usage: '/weather <get/sun/storm/thunderstorm> [swiat] [czas w tickach]'
  evaldor:
    description: 'Glowna komenda pluginu.'
    usage: '/evaldor <reload>'
  spawn:
    description: 'Teleportuje na spawn.'
    usage: '/spawn [nazwa spawnu] [gracz]'
  setspawn:
    description: 'Ustawia spawn.'
    usage: '/setspawn [nazwa spawnu]'
  fly:
    description: 'Pozwala na latanie bez tryby kreatywnego.'
    usage: '/fly <on/off>'
  heal:
    description: 'Komenda sluzaca do leczenia siebie i innych graczy.'
    usage: '/heal [gracz]'
  feed:
    description: 'Pozwala na karmienie siebie i innych graczy.'
    usage: '/feed [gracz]'
  sethealth:
    description: 'TODO'
    usage: '/sethealth [gracz] <ilosc punktow zycia>'
  sethunger:
    description: 'TODO'
    usage: '/sethunger [gracz] <ilosc punktow glodu>'